server:
  port: 8080

spring:
  application:
    name: toy-advertisement-backend
  datasource:
    url: jdbc:mysql://localhost:3306/adsdb
    username: adsuser
    password: adspw123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: 'jdbc:h2:~/ads'
#    username: adsuser
#    password: adspw123

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    mongodb:
      host: localhost
      port: 27017
      database: ads_join

    redis:
      host: localhost
      port: 6379
  main:
    allow-circular-references: true
