POST http://localhost:8080/api/v1/ads
Content-Type: application/json

{
  "name": "test11",
  "reward": 1100,
  "joinCount": 10,
  "text": "text",
  "imageUrl": "url",
  "startDate": "2024-09-11T00:20:00",
  "endDate": "2024-09-17T23:59:00"
}

###
GET http://localhost:8080/api/v1/ads/currentDisplayAdsList


###
POST http://localhost:8080/api/v1/joinAd
Content-Type: application/json

{
  "userId": "userId10",
  "adId": "ads2409110018191wjg2ke4rcewn"
}

###
GET http://localhost:8080/api/v1/joinAd/userId2/list